### ISSUE TITLE
Describe the issue/request

### ISSUE THREAD

**Issue by antonvdl** [chainguard-images/images#437]
### Which image/versions are related to this issue/feature request?

cgr.dev/chainguard/busybox:latest

### Issue/Feature description

There is a /bin/bash symlink to /bin/busybox; however busybox doesn't have an bash applet.

Running /bin/bash or /bin/busybox bash results in the following error:
/bin $ /bin/bash
bash: applet not found

/bin $ /bin/busybox bash
bash: applet not found

This causes problems when used in Gitlab runner where a shell detection script checks which shell to choose; /bin/bash is found and used but isn't working.

Please remove the /bin/bash symlink to fix this issue.

**Comment by imjasonh** [comment]
Thanks for reporting this!

Apko is responsible for creating symlinks for busybox, since it doesn't run scriptlets at install time.

The list of symlinks to create is generated, and managed here: https://github.com/chainguard-dev/apko/blob/5e8ca1aa54b5052da557a59584003a4f93080e4a/pkg/build/busybox_versions.go

The busybox image has 1.36, which is supposed to have bash symlinked: https://github.com/chainguard-dev/apko/blob/5e8ca1aa54b5052da557a59584003a4f93080e4a/pkg/build/busybox_versions.go#L3092

**Comment by imjasonh** [comment]
According to this, it does have /bin/bash as a symlink: https://explore.ggcr.dev/layers/cgr.dev/chainguard/busybox@sha256:d5ef27fbef66f6ce050b2cd0b1de98aaf24ea738dd086aa5c0de21a8cb3221f2/bin/

**Comment by tuananh** [comment]
#467 seems related.

**Comment by imjasonh** [comment]
Let's consolidate on #467
