### ISSUE TITLE
Correct fluentd tags (remove edge and update latest)

### ISSUE THREAD

**Issue by found-it** [chainguard-images/images#582]
### Which image/versions are related to this issue/feature request?

* cgr.dev/chainguard/fluentd:edge
* cgr.dev/chainguard/fluentd:latest

### Issue/Feature description

When I built these images, I misinterpreted the tagging details of the upstream images ([here](https://github.com/fluent/fluentd-docker-image/blob/master/README.md#the-detail-of-image-tag)). The `edge` tag is technically the `latest` tag by Chainguard definition being the latest version of `fluentd`.

## Proposal

1. Remove the cgr.dev/chainguard/fluentd:edge image entirely
2. Consolidate the fluentd packages in Wolfi into a single fluentd package which tracks the latest version of fluentd
3. Switch cgr.dev/chainguard/fluentd:latest to track the latest version of fluentd

**Comment by imjasonh** [comment]
This plan sounds good to me. @amouat do you foresee any issues?

We can use the nginx change as a template.

**Comment by amouat** [comment]
Sorry, I meant to reply.

Fluentd does seem to have a few users, so be a little careful. I think the plan is good, just do the same thing as per nginx:

 - warn about change, put it on the repo
 - consider having a temporary tag that is the new image for people to try (although I think that's maybe edge atm?)
 - make the change at some point in the future
 
It's probably an idea to try to identify some of the users, but beyond GitHub search, I'm not sure how to do that.

Also, don't hesitate about this, getting it done sooner rather than later is important.
