### ISSUE TITLE
Go 1.21 Fails to Build

### ISSUE THREAD

**Issue by gerred** [chainguard-images/images#982]
### Which image/versions are related to this issue/feature request?

Go 1.21

### Issue/Feature description

Getting the following issue consistently when building with the 1.21 image related to GOPROXY. Output is truncated to just the relevant parts:

```
 => ERROR [build 8/8] RUN GOOS=linux GOARCH=amd64  CGO_ENABLED=0 go build -ldflags '-extldflags "-s  0.1s
#0 0.064 api/config/config.go:4:2: GOPROXY list is not the empty string, but contains no entries
#0 0.064 pkg/client/audio/audio_grpc.pb.go:11:2: GOPROXY list is not the empty string, but contains no entries
#0 0.064 pkg/client/audio/audio_grpc.pb.go:12:2: GOPROXY list is not the empty string, but contains no entries
#0 0.064 pkg/client/audio/audio_grpc.pb.go:13:2: GOPROXY list is not the empty string, but contains no entries
#0 0.064 pkg/client/audio/audio.pb.go:10:2: GOPROXY list is not the empty string, but contains no entries
#0 0.064 pkg/client/audio/audio.pb.go:11:2: GOPROXY list is not the empty string, but contains no entries
#0 0.064 api/main.go:17:2: GOPROXY list is not the empty string, but contains no entries
#0 0.064 api/main.go:18:2: GOPROXY list is not the empty string, but contains no entries
```

Go 1.20 builds successfully. Go 1.21rc2 binary builds locally correctly, even with GOPROXY set the same as in the Chainguard image.

In `go env`:

`GOPROXY=''`

**Comment by imjasonh** [comment]
Thanks for reporting this! I'm able to reproduce with our image and not `golang:1.21`, so this is something for us to fix.

I'll add a test that our image can be used to build an app that has an external dependency, which is something we hadn't had coverage for before.

**Comment by imjasonh** [comment]
Just to wrap this up, the issue was that Go 1.21 started considering the contents of `$GOROOT/go.env` when determining things like `GOPROXY` and more, and we weren't including that file.

- https://github.com/golang/go/commit/a6a25869f07beeca8d4a2098d9f896a8a10f5b1e for more info
- https://github.com/wolfi-dev/os/commit/b9f91cb3604a9014386b03fb2399a575b501ba8f for @jonjohnsonjr 's fix (he found the issue)

#1106 added a test that packages with external dependencies can be built, and this passed after Jon's change.

Thanks again for reporting this! Let us know if anything else looks suspect, this is really helpful for vetting out the image before the real release!
